nodeLinker: node-modules

npmPublishRegistry: 'https://nexus.p42.at/repository/npm-midnight'

npmScopes:
  midnight:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://nexus.p42.at/repository/npm-midnight'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
