nodeLinker: node-modules

npmPublishRegistry: 'https://npm.pkg.github.com/'

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

packageExtensions:
  '@midnight-ntwrk/wallet@3.7.1-hardfork-rc.2':
    dependencies:
      '@midnight-ntwrk/zswap_v2': 'npm:@midnight-ntwrk/zswap@3.0.0-hard-fork-test'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
