yarnPath: .yarn/releases/yarn-4.3.1.cjs

nodeLinker: node-modules

npmScopes:
  midnight-ntwrk:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
