yarnPath: .yarn/releases/yarn-4.3.1.cjs

# with setting below, pnpm linker allows to deduplicate packages despite multiple node_modules directories
nodeLinker: pnpm

# this setting fixes issues in hard fork tests (it only affects dependencies of "wallet@3.7.1-hardfork-rc.2" wallet):
# "Cannot find module '@midnight-ntwrk/zswap_v2' from
# '../../../node_modules/.store/@midnight-ntwrk-wallet-npm-3.7.1-hardfork-rc.2-438265021f/package/dist/main.js'"
packageExtensions:
  "@midnight-ntwrk/wallet@3.7.1-hardfork-rc.2":
    dependencies:
      "@midnight-ntwrk/zswap_v2": "npm:@midnight-ntwrk/zswap@3.0.0-hard-fork-test"

# sbt subprojects need to have their own node_modules directories for ScalablyTyped to work
nmHoistingLimits: "workspaces"

npmPublishRegistry: "https://npm.pkg.github.com/"

npmScopes:
  midnight-ntwrk:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
