nodeLinker: node-modules

npmPublishRegistry: 'https://npm.pkg.github.com/'

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: false
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  '@midnight-ntwrk/wallet@3.7.1-hardfork-rc.2':
    dependencies:
      '@midnight-ntwrk/zswap_v2': 'npm:@midnight-ntwrk/zswap@3.0.0-hard-fork-test'

yarnPath: .yarn/releases/yarn-4.10.3.cjs