yarnPath: .yarn/releases/yarn-4.3.1.cjs

# with setting below, pnpm linker allows to deduplicate packages despite multiple node_modules directories
nodeLinker: pnpm

# sbt subprojects need to have their own node_modules directories for ScalablyTyped to work
nmHoistingLimits: "workspaces"

npmPublishRegistry: "https://npm.pkg.github.com/"

npmScopes:
  midnight-ntwrk:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
