approvedGitRepositories:
  - "**"

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmPreapprovedPackages:
  - "@midnightntwrk/ledger-v9"

npmPublishRegistry: "https://npm.pkg.github.com/"

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
