nodeLinker: node-modules
enableMirror: false
enableTelemetry: false

npmScopes:
  midnight:
    npmRegistryServer: https://nexus.p42.at/repository/npm-midnight/
    npmPublishRegistry: https://nexus.p42.at/repository/npm-midnight/
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN:-}
