flowchart TD
    Adresses[Night Address + registered Dust Address]
    
    NU1[Night UTxO #1]
    NU2[Night UTxO #2]
    NU3[Night UTxO #3]
    NU4[Night UTxO #4]

    Adresses -->|owns| NU1
    Adresses -->|owns| NU2
    Adresses -->|owns| NU3
    Adresses -->|owns| NU4

    DG2[Dust Generation #2]
    DG3[Dust Generation #3]
    DG4[Dust Generation #4]

    NU2 -->|generates| DG2
    NU3 -->|generates| DG3
    NU4 -->|generates| DG4

    DUI2[Dust Initial UTxO #2]
    DUI3[Dust Initial UTxO #3]
    DUI4[Dust Initial UTxO #4]

    DG2 -->|generates| DUI2
    DG3 -->|generates| DUI3
    DG4 -->|generates| DUI4

    DU31[Dust UTxO #3,1]
    DU41[Dust UTxO #4,1]
    DU42[Dust UTxO #4,2]
    DU4N[Dust UTxO #4,N]

    DUI3 -->|dust spend| DU31
    DUI4 -->|dust spend| DU41
    DU41 -->|dust spend| DU42
    DU42 -->|... dust spends ...| DU4N