// This file is part of MIDNIGHT-WALLET-SDK.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import { Data } from 'effect';
import { type SnapshotFormat } from '@midnightntwrk/wallet-sdk-abstractions';
import { type LedgerOps } from '@midnightntwrk/wallet-sdk-utilities';

export class OtherWalletError extends Data.TaggedError('Wallet.Other')<{
  message: string;
  cause?: unknown;
}> {}

export class SyncWalletError extends Data.TaggedError('Wallet.Sync')<{
  message: string;
  cause?: unknown;
}> {}

export class TransactingError extends Data.TaggedError('Wallet.Transacting')<{
  message: string;
  cause?: unknown;
}> {}

export class InsufficientFundsError extends Data.TaggedError('Wallet.InsufficientFunds')<{
  message: string;
  tokenType: string;
}> {}

export class TransactionHistoryError extends Data.TaggedError('Wallet.TransactionHistory')<{
  message: string;
  cause?: unknown;
}> {}

/**
 * A finalized history entry that records no block, met where a block is needed.
 *
 * @remarks
 *   Only an entry restored from a history written before the lifecycle field existed looks like this: it is known to have
 *   been finalized, but the block it landed in was never recorded, and none is invented. It is its own error rather
 *   than a message on {@link TransactionHistoryError} so that a caller which can fetch the block by hash matches on the
 *   tag.
 * @example
 *   ```ts
 *   if (error._tag === 'Wallet.BlocklessFinalizedEntry') fetchBlockFor(error.hash);
 *   ```;
 */
export class BlocklessFinalizedEntryError extends Data.TaggedError('Wallet.BlocklessFinalizedEntry')<{
  readonly message: string;
  /** The transaction whose history entry records no block. */
  readonly hash: string;
}> {}

/**
 * A batch of dust ledger events was not in ascending id order: an event arrived at or below the one before it, or at or
 * below the applied cursor.
 *
 * @remarks
 *   Order is all the wallet can check: dust events share one id sequence with zswap and contract events in the indexer,
 *   so gaps in the stream are normal and a skipped event is only ever caught by the ledger's own insertion check. The
 *   whole batch is refused, nothing is applied and the cursor stays, so the running variant retries from the same
 *   place.
 * @example
 *   ```ts
 *   if (error._tag === 'Wallet.OutOfOrderSyncUpdate') console.warn(`expected above ${error.expected}, got ${error.received}`);
 *   ```
 */
export class OutOfOrderSyncUpdateError extends Data.TaggedError('Wallet.OutOfOrderSyncUpdate')<{
  readonly message: string;
  /** The id the delivered event had to exceed: its predecessor in the batch, or the applied cursor. */
  readonly expected: bigint;
  /** The event id the source delivered instead. */
  readonly received: bigint;
}> {}

/**
 * When the claimable fee payment of a set of Night UTxOs will reach a fee, or why it never will.
 *
 * @remarks
 *   `Reachable` gives the first whole second, counted from the time the estimate was made, at which the dust generated by
 *   some unregistered UTxO covers the fee; `seconds` is `0n` when one already does. `Unreachable` says no such second
 *   exists: `NoGeneration` when no unregistered UTxO generates any dust, `ExceedsCap` when some do but the fee is above
 *   the most any of them can ever hold.
 * @example
 *   ```ts
 *   const deadline = estimate._tag === 'Reachable' ? estimate.at : undefined; // undefined: waiting will not help
 *   ```;
 */
export type FeeCoverageEstimate =
  | { readonly _tag: 'Reachable'; readonly seconds: bigint; readonly at: Date }
  | { readonly _tag: 'Unreachable'; readonly reason: 'NoGeneration' | 'ExceedsCap' };

/** A deadline for `waitForGeneratedDust` that sees an estimate of `seconds` out, with a minute to spare. */
const waitTimeoutMs = (seconds: bigint): bigint => seconds * 1000n + 60_000n;

const UNREACHABLE_REASONS: Record<Extract<FeeCoverageEstimate, { _tag: 'Unreachable' }>['reason'], string> = {
  NoGeneration: 'none of the unregistered Night UTxOs generates dust',
  ExceedsCap: 'the fee is above the most dust any unregistered Night UTxO can generate',
};

/**
 * A first-time registration cannot pay its own fee yet: the dust its unregistered Night has generated falls short.
 *
 * @remarks
 *   Amounts are in Specks. `shortfall` is `fee - claimableFeePayment`, and `estimate` says when generation closes it, if
 *   ever — the same moment `waitForGeneratedDust` would resolve for that fee.
 * @example
 *   ```ts
 *   if (error._tag === 'Wallet.InsufficientDustForFee' && error.estimate._tag === 'Reachable')
 *   console.warn(`short by ${error.shortfall} Specks, covered at ${error.estimate.at.toISOString()}`);
 *   ```
 */
export class InsufficientDustForFeeError extends Data.TaggedError('Wallet.InsufficientDustForFee')<{
  readonly message: string;
  /** The dust the registration may claim for its own fee now. */
  readonly claimableFeePayment: bigint;
  /** The fee the registration needs. */
  readonly fee: bigint;
  /** How far `claimableFeePayment` falls below `fee`. */
  readonly shortfall: bigint;
  /** When `claimableFeePayment` reaches `fee`, or why it never will. */
  readonly estimate: FeeCoverageEstimate;
}> {
  /**
   * Builds the error from what was read, deriving the shortfall and the message.
   *
   * @param reading The claimable fee payment, the fee and the estimate of when one reaches the other.
   * @returns The error.
   */
  static of(reading: {
    readonly claimableFeePayment: bigint;
    readonly fee: bigint;
    readonly estimate: FeeCoverageEstimate;
  }): InsufficientDustForFeeError {
    const headline = `Insufficient generated dust to cover registration fee (have ${reading.claimableFeePayment}, need ${reading.fee}).`;
    const outlook =
      reading.estimate._tag === 'Reachable'
        ? `Generated dust should cover it in about ${reading.estimate.seconds} s (at ${reading.estimate.at.toISOString()}). ` +
          `Use WalletFacade.waitForGeneratedDust(utxos, ${reading.fee}, { timeoutMs: ${waitTimeoutMs(reading.estimate.seconds)} }) before retrying.`
        : `It never will: ${UNREACHABLE_REASONS[reading.estimate.reason]}.`;
    return new InsufficientDustForFeeError({
      ...reading,
      shortfall: reading.fee - reading.claimableFeePayment,
      message: `${headline} ${outlook}`,
    });
  }
}

export type WalletError =
  | SnapshotFormat.SnapshotRestoreError
  | OtherWalletError
  | SyncWalletError
  | TransactingError
  | InsufficientFundsError
  | TransactionHistoryError
  | OutOfOrderSyncUpdateError
  | InsufficientDustForFeeError
  | LedgerOps.LedgerError;
