// Regenerate the frozen ECDSA/Schnorr golden vectors:
//   node packages/unshielded-wallet/test/fixtures/generate.mjs
// Provenance for ecdsaVectors.json. Values come from the real ledger-v9 +
// wallet-sdk-hd pipeline and are cross-checked against the @noble/curves oracle.
import { writeFileSync } from 'node:fs';
import * as ledger from '@midnightntwrk/ledger-v9';
import { HDWallet, Roles } from '@midnightntwrk/wallet-sdk-hd';
import { UnshieldedAddress } from '@midnightntwrk/wallet-sdk-address-format';
import { NetworkId } from '@midnightntwrk/wallet-sdk-abstractions';
import { secp256k1, schnorr } from '@noble/curves/secp256k1';
import { sha256 } from '@noble/hashes/sha2';

const networkId = NetworkId.NetworkId.Undeployed;
const hexOf = (u) => Buffer.from(u).toString('hex');
const bytes = (h) => Uint8Array.from(Buffer.from(h, 'hex'));

const seed = Buffer.alloc(32, 1);
const message = 'attack at dawn';
const data = new TextEncoder().encode(message);

const hw = HDWallet.fromSeed(seed);
if (hw.type !== 'seedOk') throw new Error('seed failed');
const deriveSecret = (role) => {
  const r = hw.hdWallet.selectAccount(0).selectRole(role).deriveKeyAt(0);
  if (r.type !== 'keyDerived') throw new Error('derive failed for role ' + role);
  return r.key;
};
const bech32Of = (addressHex) =>
  UnshieldedAddress.codec.encode(networkId, new UnshieldedAddress(Buffer.from(addressHex, 'hex'))).asString();

const vectorFor = (kind, role) => {
  const secret = deriveSecret(role);
  const sk = { tag: kind, value: hexOf(secret) };
  const vk = ledger.signatureVerifyingKey(sk);
  const addressHex = ledger.addressFromKey(vk);
  const sig = ledger.signData(sk, data);
  const deterministic = ledger.signData(sk, data).value === sig.value;
  const oracleVerified =
    kind === 'ecdsa'
      ? secp256k1.verify(bytes(sig.value), sha256(data), bytes(vk.value))
      : schnorr.verify(bytes(sig.value), sha256(data), bytes(vk.value));
  if (!ledger.verifySignature(vk, data, sig) || !oracleVerified) throw new Error('verify failed for ' + kind);
  return {
    kind,
    hdRole: role,
    privateKey: hexOf(secret),
    verifyingKey: vk.value,
    verifyingKeyBytes: vk.value.length / 2,
    addressHex,
    bech32Address: bech32Of(addressHex),
    signatureDeterministic: deterministic,
    // BIP340 schnorr uses a randomized nonce → no stable signature to freeze;
    // verify via the oracle instead. ECDSA is RFC-6979 deterministic → frozen.
    signature: deterministic ? sig.value : null,
  };
};

const out = {
  _comment:
    'Frozen golden vectors generated by test/fixtures/generate.mjs from the real ledger-v9 + wallet-sdk-hd pipeline. Do not hand-edit; regenerate and review diffs. The ledger signs sha256(message) under both schemes.',
  ledgerVersion: '0.1.0-alpha.1',
  networkId: 'undeployed',
  derivation: {
    purpose: 44,
    coinType: 2400,
    account: 0,
    index: 0,
    pathTemplate: "m/44'/2400'/0'/<hdRole>/0",
    seedHex: hexOf(seed),
  },
  message: { utf8: message, hex: hexOf(data), signedDigest: 'sha256' },
  schnorr: vectorFor('schnorr', Roles.NightExternal),
  ecdsa: vectorFor('ecdsa', Roles.EcdsaUnshielded),
};
writeFileSync(new URL('./ecdsaVectors.json', import.meta.url), JSON.stringify(out, null, 2) + '\n');
console.log(JSON.stringify(out, null, 2));
