// This file is part of MIDNIGHT-WALLET-SDK.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import {
  Array as EArray,
  BigInt as BigIntOps,
  Data,
  Either,
  Iterable as IterableOps,
  Match,
  Option,
  pipe,
} from 'effect';
import {
  DustActions,
  DustRegistration,
  type DustSecretKey,
  Intent,
  type PreBinding,
  type PreProof,
  type Signature,
  SignatureEnabled,
  type SignatureVerifyingKey,
  Transaction,
  UnshieldedOffer,
  type UtxoOutput,
  type UtxoSpend,
  type FinalizedTransaction,
  type ProofErasedTransaction,
  type UnprovenTransaction,
  addressFromKey,
  type LedgerParameters,
  nativeToken,
} from '@midnight-ntwrk/ledger-v8';
import { type DustAddress } from '@midnightntwrk/wallet-sdk-address-format';
import { OtherWalletError, TransactingError, type WalletError, InsufficientFundsError } from './WalletError.js';
import { LedgerOps } from '@midnightntwrk/wallet-sdk-utilities';
import { CoreWallet } from './CoreWallet.js';
import { type AnyTransaction, type Dust, type NetworkId, type TotalCostParameters } from './types/index.js';
import {
  type CoinsAndBalancesCapability,
  type CoinSelection,
  type CoinWithValue,
  type UtxoWithFullDustDetails,
} from './CoinsAndBalances.js';
import { type KeysCapability } from './Keys.js';
import { BindingMarker, ProofMarker, SignatureMarker } from './Utils.js';
import {
  getBalanceRecipe,
  Imbalances as CapImbalances,
  InsufficientFundsError as BalancingInsufficientFundsError,
} from '@midnightntwrk/wallet-sdk-capabilities';

/**
 * Result of splitting Night UTxOs into the guaranteed/fallible sections of a Dust registration or deregistration
 * intent, together with the fee-payment allowance the registration may claim from dust generated by the guaranteed
 * UTxO.
 *
 * For deregistration, `feePayment` is always `0n`.
 */
export type NightUtxoSplitForDustRegistration = {
  readonly guaranteedUtxos: ReadonlyArray<UtxoWithFullDustDetails>;
  readonly fallibleUtxos: ReadonlyArray<UtxoWithFullDustDetails>;
  readonly feePayment: bigint;
};

// This interface should abstract over the transaction types used
// It does not do so now for historical reasons
export interface TransactingCapability<TSecrets, TState, _TTransaction> {
  readonly networkId: NetworkId;
  readonly costParams: TotalCostParameters;
  createDustGenerationTransaction(
    currentTime: Date,
    ttl: Date,
    nightUtxos: ReadonlyArray<UtxoWithFullDustDetails>,
    nightVerifyingKey: SignatureVerifyingKey,
    dustReceiverAddress: DustAddress | undefined,
  ): Either.Either<UnprovenTransaction, WalletError>;

  /**
   * Decides which Night UTxOs belong in the guaranteed vs fallible section of a dust registration/deregistration
   * transaction, and computes the fee-payment allowance the registration may claim from dust generated by the
   * guaranteed UTxO.
   *
   * For deregistration (`isRegistration === false`) the fee-payment allowance is always `0n`.
   */
  splitNightUtxosForDustRegistration(
    utxosWithDustValue: ReadonlyArray<UtxoWithFullDustDetails>,
    isRegistration: boolean,
  ): NightUtxoSplitForDustRegistration;

  /**
   * Attaches a Dust registration / deregistration action onto the intent (at segment 1) of an unproven transaction
   * whose offers have already been built (typically by the unshielded wallet's `rotateUtxos`). The Night UTxOs are
   * assumed to already appear in the intent's guaranteed/fallible offers and to already be booked in the unshielded
   * wallet state.
   */
  attachDustRegistration(
    transaction: UnprovenTransaction,
    currentTime: Date,
    nightVerifyingKey: SignatureVerifyingKey,
    dustReceiverAddress: DustAddress | undefined,
    feePayment: bigint,
  ): Either.Either<UnprovenTransaction, WalletError>;

  addDustGenerationSignature(
    transaction: UnprovenTransaction,
    signature: Signature,
  ): Either.Either<UnprovenTransaction, WalletError>;

  /**
   * Attaches a signature to the DustRegistration in segment 1's `dustActions` only. Unlike
   * {@link addDustGenerationSignature}, this does NOT touch the unshielded offers — those are expected to be signed via
   * the unshielded-wallet signing path. Use this when the caller orchestrates signing across both packages (e.g. the
   * facade's `signRecipe`).
   */
  addDustRegistrationSignature(
    transaction: UnprovenTransaction,
    signature: Signature,
  ): Either.Either<UnprovenTransaction, WalletError>;

  calculateFee(transaction: AnyTransaction, ledgerParams: LedgerParameters): bigint;

  estimateFee(
    secretKey: TSecrets,
    state: TState,
    transactions: ReadonlyArray<AnyTransaction>,
    ttl: Date,
    currentTime: Date,
    ledgerParams: LedgerParameters,
  ): Either.Either<bigint, WalletError>;

  balanceTransactions(
    secretKey: TSecrets,
    state: TState,
    transactions: ReadonlyArray<AnyTransaction>,
    ttl: Date,
    currentTime: Date,
    ledgerParams: LedgerParameters,
  ): Either.Either<[UnprovenTransaction, TState], WalletError>;

  revertTransaction(state: TState, transaction: AnyTransaction): Either.Either<TState, WalletError>;
}

export type DefaultTransactingConfiguration = {
  networkId: NetworkId;
  costParameters: TotalCostParameters;
};

export type DefaultTransactingContext = {
  coinSelection: CoinSelection;
  coinsAndBalancesCapability: CoinsAndBalancesCapability<CoreWallet>;
  keysCapability: KeysCapability<CoreWallet>;
};

export const makeDefaultTransactingCapability = (
  config: DefaultTransactingConfiguration,
  getContext: () => DefaultTransactingContext,
): TransactingCapability<DustSecretKey, CoreWallet, FinalizedTransaction> => {
  return new TransactingCapabilityImplementation(
    config.networkId,
    config.costParameters,
    () => getContext().coinSelection,
    () => getContext().coinsAndBalancesCapability,
    () => getContext().keysCapability,
  );
};

export const makeSimulatorTransactingCapability = (
  config: DefaultTransactingConfiguration,
  getContext: () => DefaultTransactingContext,
): TransactingCapability<DustSecretKey, CoreWallet, ProofErasedTransaction> => {
  return new TransactingCapabilityImplementation(
    config.networkId,
    config.costParameters,
    () => getContext().coinSelection,
    () => getContext().coinsAndBalancesCapability,
    () => getContext().keysCapability,
  );
};

/**
 * Distributes the fee across multiple inputs, draining smaller inputs first when the fee exceeds any single input's
 * value. Finds the next available intent segment id in a transaction.
 *
 * Fallible intent segments occupy the range `[1, 65535]`; segment `0` is reserved for the guaranteed section and is
 * never returned.
 *
 * @param transaction - Transaction whose intent map is inspected.
 * @returns `Some(segmentId)` with the lowest unused id, or `None` if all 65535 fallible segments are taken.
 */
export const findAvailableSegmentId = (transaction: AnyTransaction): Option.Option<number> => {
  const used = new Set(transaction.intents?.keys() ?? []);
  return pipe(
    IterableOps.range(1, 65535),
    IterableOps.findFirst((segmentId) => !used.has(segmentId)),
  );
};

/**
 * Distributes the fee across multiple inputs, draining smaller inputs first when the fee exceeds any single input's
 * value.
 */
const distributeFeeAcrossInputs = <T extends { value: bigint }>(
  inputs: ReadonlyArray<T>,
  fee: bigint,
): ReadonlyArray<T> =>
  inputs.reduce<{ result: T[]; remaining: bigint }>(
    ({ result, remaining }, input) => {
      const deduction = remaining >= input.value ? input.value : remaining;
      return { result: [...result, { ...input, value: deduction }], remaining: remaining - deduction };
    },
    { result: [], remaining: fee },
  ).result;

/** The transactions being balanced, proof-erased and merged once, with the segment a balancing intent may use. */
type MergedTransactions = {
  readonly transaction: ProofErasedTransaction;
  readonly segmentId: number;
};

/**
 * Proof-erases and merges the transactions being balanced. This does not depend on which dust inputs are being priced,
 * so callers pricing several input sets against the same transactions do it once, not once per pass. `None` when there
 * is nothing to balance against. May throw: it is ledger arithmetic, and callers wrap it in `LedgerOps.ledgerTry`.
 */
const mergeErasedTransactions = (
  transactions: ReadonlyArray<FinalizedTransaction | UnprovenTransaction>,
): Option.Option<MergedTransactions> =>
  pipe(
    transactions.map((tx) => tx.eraseProofs()),
    EArray.match({
      onEmpty: () => Option.none(),
      onNonEmpty: ([first, ...rest]) => {
        const transaction = rest.reduce((acc, tx) => acc.merge(tx), first);
        return Option.some({
          transaction,
          segmentId: Option.getOrElse(findAvailableSegmentId(transaction), () => 1),
        });
      },
    }),
  );

/** What `computeBalancingRecipe` produces: the total fee of the balanced result and what each selected coin pays. */
type DustBalancingRecipe = {
  readonly fee: bigint;
  readonly recipeInputs: ReadonlyArray<CoinWithValue<Dust>>;
};

/** The pool ran out under the configured order before the fee was covered — an ordering artefact, retried largest-first. */
class SelectionExhausted extends Data.TaggedError('DustBalancing.SelectionExhausted')<{
  readonly message: string;
}> {}

/** The configured selector declined the coins it was offered — a policy, honoured as-is and never retried. */
class SelectionRefused extends Data.TaggedError('DustBalancing.SelectionRefused')<{
  readonly remaining: number;
}> {}

/** The selector returned coins that were not among those offered, so a pass consumed nothing and could not progress. */
class SelectionMadeNoProgress extends Data.TaggedError('DustBalancing.SelectionMadeNoProgress')<{
  readonly returned: number;
  readonly remaining: number;
}> {}

/** `getBalanceRecipe` threw something other than its insufficient-funds error. */
class BalancerFailed extends Data.TaggedError('DustBalancing.BalancerFailed')<{
  readonly cause: unknown;
}> {}

type SelectionFailure = SelectionExhausted | SelectionRefused | SelectionMadeNoProgress | BalancerFailed;

/**
 * Picks the largest-value coin from the pool. Used only for the one retry inside `computeBalancingRecipe`, when the
 * configured order exhausts the pool with an affordable set of coins left unselected; not exported, since it is that
 * loop's last resort rather than a general-purpose selector.
 */
const largestFirst: CoinSelection = (coins) =>
  coins
    .filter((coin) => coin.value > 0n)
    .toSorted((a, b) => (b.value > a.value ? 1 : b.value < a.value ? -1 : 0))
    .at(0);

/**
 * A selector declines by returning `undefined`, and the balancer folds that into the same `InsufficientFundsError` it
 * throws for an exhausted pool. The two must stay distinguishable — declining is the caller's policy and must never be
 * overridden by the largest-first retry — so a decline on a non-empty pool is surfaced as its own failure here.
 * Throwing is the only way out of `getBalanceRecipe`, whose failure contract is exceptions; it is caught by the
 * `Either.try` in `selectForDeficit` and never leaves this module.
 */
const surfacingRefusal =
  (coinSelection: CoinSelection): CoinSelection =>
  (coins) => {
    const chosen = coinSelection(coins);
    if (chosen === undefined && coins.length > 0) {
      throw new SelectionRefused({ remaining: coins.length });
    }
    return chosen;
  };

/**
 * One pass of selection: coins from `remaining`, in the configured order, until their value covers `deficit` plus
 * `inputFeeOverhead` for each coin taken. Returned in selection order — `distributeFeeAcrossInputs` relies on that to
 * drain the coins chosen first (under the default order, the smaller ones) before touching the later ones.
 */
const selectForDeficit = (
  remaining: ReadonlyArray<CoinWithValue<Dust>>,
  deficit: bigint,
  inputFeeOverhead: bigint,
  coinSelection: CoinSelection,
): Either.Either<EArray.NonEmptyReadonlyArray<CoinWithValue<Dust>>, SelectionFailure> =>
  pipe(
    Either.try({
      try: () =>
        getBalanceRecipe({
          coins: remaining.map((coin) => ({ type: 'dust', value: coin.value, token: coin.token })),
          initialImbalances: CapImbalances.fromEntry('dust', -deficit),
          feeTokenType: 'dust',
          coinSelection: surfacingRefusal(coinSelection),
          transactionCostModel: { inputFeeOverhead, outputFeeOverhead: 0n },
          createOutput: (coin) => coin,
          isCoinEqual: (a, b) => a.token.nonce === b.token.nonce,
        }),
      catch: (err): SelectionFailure =>
        err instanceof SelectionRefused
          ? err
          : err instanceof BalancingInsufficientFundsError
            ? new SelectionExhausted({ message: err.message })
            : new BalancerFailed({ cause: err }),
    }),
    Either.flatMap((recipe) => {
      const added = EArray.filterMap(recipe.inputs, (input) =>
        EArray.findFirst(remaining, (coin) => coin.token.nonce === input.token.nonce),
      );
      return EArray.isNonEmptyReadonlyArray(added)
        ? Either.right(added)
        : Either.left(new SelectionMadeNoProgress({ returned: recipe.inputs.length, remaining: remaining.length }));
    }),
  );

/**
 * The fee grows with every dust input, and the balancer can anticipate that through `inputFeeOverhead`, which it
 * subtracts from the outstanding deficit per coin it takes. The ledger's cost model does not expose the figure, so it
 * is measured: the fee increase over the base fee so far, averaged over the inputs taken, rounded up. Zero until the
 * first pass has priced something, so that pass selects on raw value and later passes complete what it left short.
 */
const marginalFeePerInput = (feeIncrease: bigint, inputs: number): bigint =>
  inputs === 0 || feeIncrease <= 0n ? 0n : (feeIncrease + BigInt(inputs) - 1n) / BigInt(inputs);

/**
 * Selects dust inputs until, together with the dust the transactions already carry, they cover the fee of the
 * transaction they produce. Each pass covers only the outstanding deficit from the coins not yet selected, then
 * re-prices with everything selected so far. A pass that takes no coin fails as `SelectionMadeNoProgress`, so every
 * pass shrinks `remaining` and the recursion is bounded by the pool size.
 */
const selectDustInputs = (args: {
  readonly coins: ReadonlyArray<CoinWithValue<Dust>>;
  readonly baseFee: bigint;
  readonly existingDust: bigint;
  readonly feeWith: (
    inputs: EArray.NonEmptyReadonlyArray<CoinWithValue<Dust>>,
  ) => Either.Either<bigint, LedgerOps.LedgerError>;
  readonly coinSelection: CoinSelection;
}): Either.Either<DustBalancingRecipe, SelectionFailure | LedgerOps.LedgerError> => {
  const { baseFee, existingDust, feeWith, coinSelection } = args;
  const go = (
    remaining: ReadonlyArray<CoinWithValue<Dust>>,
    inputs: ReadonlyArray<CoinWithValue<Dust>>,
    fee: bigint,
  ): Either.Either<DustBalancingRecipe, SelectionFailure | LedgerOps.LedgerError> =>
    Either.gen(function* () {
      const covered = BigIntOps.sumAll(inputs.map((input) => input.value));
      const deficit = fee - existingDust - covered;
      if (deficit <= 0n) {
        return { fee, recipeInputs: distributeFeeAcrossInputs(inputs, fee - existingDust) };
      }
      const added = yield* selectForDeficit(
        remaining,
        deficit,
        marginalFeePerInput(fee - baseFee, inputs.length),
        coinSelection,
      );
      const nextInputs = EArray.appendAll(inputs, added);
      const nextFee = yield* feeWith(nextInputs);
      const rest = remaining.filter((coin) => !added.some((taken) => taken.token.nonce === coin.token.nonce));
      return yield* go(rest, nextInputs, nextFee);
    });
  return go(args.coins, [], baseFee);
};

/**
 * Runs selection under the configured order and, only if that exhausts the pool, once more largest-first: an additive
 * selection is guaranteed to find a covering set only when it takes coins from the top, since the k largest coins
 * dominate every other k-subset. Any other failure — a declining selector above all — is reported as it is.
 */
const selectWithLargestFirstRetry = (
  select: (
    coinSelection: CoinSelection,
  ) => Either.Either<DustBalancingRecipe, SelectionFailure | LedgerOps.LedgerError>,
  configured: CoinSelection,
): Either.Either<DustBalancingRecipe, SelectionFailure | LedgerOps.LedgerError> =>
  pipe(
    select(configured),
    Either.orElse((failure) =>
      failure._tag === 'DustBalancing.SelectionExhausted' ? select(largestFirst) : Either.left(failure),
    ),
  );

const toWalletError = (failure: SelectionFailure | LedgerOps.LedgerError): WalletError =>
  Match.value(failure).pipe(
    Match.tag(
      'DustBalancing.SelectionExhausted',
      ({ message }) => new InsufficientFundsError({ message, tokenType: 'dust' }),
    ),
    Match.tag(
      'DustBalancing.SelectionRefused',
      ({ remaining }) =>
        new InsufficientFundsError({
          message: `Insufficient Funds: the configured coin selection declined the remaining ${remaining} dust coin(s)`,
          tokenType: 'dust',
        }),
    ),
    Match.tag(
      'DustBalancing.SelectionMadeNoProgress',
      ({ returned, remaining }) =>
        new TransactingError({
          message: `Coin selection returned ${returned} coin(s), none of them among the ${remaining} offered; a selector must pick from the coins it is given`,
        }),
    ),
    Match.tag(
      'DustBalancing.BalancerFailed',
      ({ cause }) =>
        new OtherWalletError({ message: cause instanceof Error ? cause.message : 'Dust balancing failed', cause }),
    ),
    Match.tag('LedgerError', (error) => error),
    Match.exhaustive,
  );

export class TransactingCapabilityImplementation<TTransaction extends AnyTransaction> implements TransactingCapability<
  DustSecretKey,
  CoreWallet,
  TTransaction
> {
  public readonly networkId: string;
  public readonly costParams: TotalCostParameters;
  public readonly getCoinSelection: () => CoinSelection;
  readonly getCoins: () => CoinsAndBalancesCapability<CoreWallet>;
  readonly getKeys: () => KeysCapability<CoreWallet>;

  constructor(
    networkId: NetworkId,
    costParams: TotalCostParameters,
    getCoinSelection: () => CoinSelection,
    getCoins: () => CoinsAndBalancesCapability<CoreWallet>,
    getKeys: () => KeysCapability<CoreWallet>,
  ) {
    this.getCoins = getCoins;
    this.networkId = networkId;
    this.costParams = costParams;
    this.getCoinSelection = getCoinSelection;
    this.getKeys = getKeys;
  }

  createDustGenerationTransaction(
    currentTime: Date,
    ttl: Date,
    nightUtxos: ReadonlyArray<UtxoWithFullDustDetails>,
    nightVerifyingKey: SignatureVerifyingKey,
    dustReceiverAddress: DustAddress | undefined,
  ): Either.Either<UnprovenTransaction, WalletError> {
    const makeOffer = (
      utxos: ReadonlyArray<UtxoWithFullDustDetails>,
    ): Option.Option<UnshieldedOffer<SignatureEnabled>> => {
      if (utxos.length === 0) {
        return Option.none();
      }
      const totalValue = pipe(
        utxos,
        IterableOps.map((coin) => coin.utxo.value),
        BigIntOps.sumAll,
      );
      const inputs: UtxoSpend[] = utxos.map(({ utxo }) => ({
        ...utxo,
        owner: nightVerifyingKey,
      }));
      const output: UtxoOutput = {
        owner: addressFromKey(nightVerifyingKey),
        type: nativeToken().raw,
        value: totalValue,
      };

      return Option.some(UnshieldedOffer.new(inputs, [output], []));
    };

    return Either.gen(this, function* () {
      const receiver = dustReceiverAddress ? dustReceiverAddress.data : undefined;

      return yield* LedgerOps.ledgerTry(() => {
        const network = this.networkId;

        const splitResult = this.getCoins().splitNightUtxos(nightUtxos);

        // if receiver is `undefined`, it means the coin(s) are being deregistered so the allowFeePayment should not be used
        const feePayment = receiver
          ? pipe(
              splitResult.guaranteed,
              IterableOps.filter((coin) => !coin.utxo.registeredForDustGeneration),
              IterableOps.map((coin) => coin.dust.generatedNow),
              BigIntOps.sumAll,
            )
          : 0n;

        const maybeGuaranteedOffer = makeOffer(splitResult.guaranteed);
        const maybeFallibleOffer = makeOffer(splitResult.fallible);

        const dustRegistration: DustRegistration<SignatureEnabled> = new DustRegistration(
          SignatureMarker.signature,
          nightVerifyingKey,
          receiver,
          feePayment,
        );
        const dustActions = new DustActions<SignatureEnabled, PreProof>(
          SignatureMarker.signature,
          ProofMarker.preProof,
          currentTime,
          [],
          [dustRegistration],
        );

        const intent = pipe(
          Intent.new(ttl),
          (intent) =>
            Option.match(maybeGuaranteedOffer, {
              onNone: () => intent,
              onSome: (guaranteedOffer) => {
                intent.guaranteedUnshieldedOffer = guaranteedOffer;
                return intent;
              },
            }),
          (intent) =>
            Option.match(maybeFallibleOffer, {
              onNone: () => intent,
              onSome: (fallibleOffer) => {
                intent.fallibleUnshieldedOffer = fallibleOffer;
                return intent;
              },
            }),
          (intent) => {
            intent.dustActions = dustActions;
            return intent;
          },
        );

        return Transaction.fromParts(network, undefined, undefined, intent);
      });
    });
  }

  splitNightUtxosForDustRegistration(
    utxosWithDustValue: ReadonlyArray<UtxoWithFullDustDetails>,
    isRegistration: boolean,
  ): NightUtxoSplitForDustRegistration {
    const splitResult = this.getCoins().splitNightUtxos(utxosWithDustValue);
    // Deregistration must not claim dust as fee payment (matches the historical
    // `dustReceiverAddress === undefined` branch of createDustGenerationTransaction).
    const feePayment = isRegistration
      ? pipe(
          splitResult.guaranteed,
          IterableOps.filter((coin) => !coin.utxo.registeredForDustGeneration),
          IterableOps.map((coin) => coin.dust.generatedNow),
          BigIntOps.sumAll,
        )
      : 0n;
    return {
      guaranteedUtxos: splitResult.guaranteed,
      fallibleUtxos: splitResult.fallible,
      feePayment,
    };
  }

  attachDustRegistration(
    transaction: UnprovenTransaction,
    currentTime: Date,
    nightVerifyingKey: SignatureVerifyingKey,
    dustReceiverAddress: DustAddress | undefined,
    feePayment: bigint,
  ): Either.Either<UnprovenTransaction, WalletError> {
    return Either.gen(this, function* () {
      const intent = transaction.intents?.get(1);
      if (!intent) {
        return yield* Either.left(
          new TransactingError({
            message: 'No intent found at segment 1; expected an intent built by rotateUtxos',
          }),
        );
      }
      if (intent.dustActions !== undefined && intent.dustActions.registrations.length > 0) {
        return yield* Either.left(
          new TransactingError({ message: 'Intent at segment 1 already has a dust registration attached' }),
        );
      }

      return yield* LedgerOps.ledgerTry(() => {
        const receiver = dustReceiverAddress ? dustReceiverAddress.data : undefined;
        const dustRegistration = new DustRegistration<SignatureEnabled>(
          SignatureMarker.signature,
          nightVerifyingKey,
          receiver,
          feePayment,
        );
        const dustActions = new DustActions<SignatureEnabled, PreProof>(
          SignatureMarker.signature,
          ProofMarker.preProof,
          currentTime,
          [],
          [dustRegistration],
        );

        // Intents fetched from `transaction.intents.get(...)` behave like value copies — assigning
        // to a field doesn't propagate back. Match the addDustGenerationSignature pattern: copy the
        // intent via serialize/deserialize, mutate the copy, then set it back into a fresh
        // transaction's intents map.
        const newIntent = Intent.deserialize<SignatureEnabled, PreProof, PreBinding>(
          SignatureMarker.signature,
          ProofMarker.preProof,
          BindingMarker.preBinding,
          intent.serialize(),
        );
        newIntent.dustActions = dustActions;

        const newTransaction = Transaction.deserialize<SignatureEnabled, PreProof, PreBinding>(
          SignatureMarker.signature,
          ProofMarker.preProof,
          BindingMarker.preBinding,
          transaction.serialize(),
        );
        newTransaction.intents = newTransaction.intents!.set(1, newIntent);

        return newTransaction;
      });
    });
  }

  addDustRegistrationSignature(
    transaction: UnprovenTransaction,
    signatureData: Signature,
  ): Either.Either<UnprovenTransaction, WalletError> {
    return Either.gen(this, function* () {
      const intent = transaction.intents?.get(1);
      if (!intent) {
        return yield* Either.left(
          new TransactingError({ message: 'No intent found in the transaction intents with segment = 1' }),
        );
      }

      const { dustActions } = intent;
      if (!dustActions) {
        return yield* Either.left(new TransactingError({ message: 'No dustActions found in intent' }));
      }

      const [registration, ...restRegistrations] = dustActions.registrations;
      if (!registration) {
        return yield* Either.left(new TransactingError({ message: 'No registrations found in dustActions' }));
      }

      return yield* LedgerOps.ledgerTry(() => {
        const signature = new SignatureEnabled(signatureData);
        const registrationWithSignature = new DustRegistration(
          signature.instance,
          registration.nightKey,
          registration.dustAddress,
          registration.allowFeePayment,
          signature,
        );
        const newDustActions = new DustActions(
          signature.instance,
          ProofMarker.preProof,
          dustActions.ctime,
          dustActions.spends,
          [registrationWithSignature, ...restRegistrations],
        );

        const newIntent = Intent.deserialize<SignatureEnabled, PreProof, PreBinding>(
          signature.instance,
          ProofMarker.preProof,
          BindingMarker.preBinding,
          intent.serialize(),
        );
        newIntent.dustActions = newDustActions;

        const newTransaction = Transaction.deserialize<SignatureEnabled, PreProof, PreBinding>(
          signature.instance,
          ProofMarker.preProof,
          BindingMarker.preBinding,
          transaction.serialize(),
        );
        newTransaction.intents = newTransaction.intents!.set(1, newIntent);

        return newTransaction;
      });
    });
  }

  addDustGenerationSignature(
    transaction: UnprovenTransaction,
    signatureData: Signature,
  ): Either.Either<UnprovenTransaction, WalletError> {
    return Either.gen(this, function* () {
      const intent = transaction.intents?.get(1);
      if (!intent) {
        return yield* Either.left(
          new TransactingError({ message: 'No intent found in the transaction intents with segment = 1' }),
        );
      }

      const { dustActions, guaranteedUnshieldedOffer, fallibleUnshieldedOffer } = intent;
      if (!dustActions) {
        return yield* Either.left(new TransactingError({ message: 'No dustActions found in intent' }));
      }

      if (!guaranteedUnshieldedOffer) {
        return yield* Either.left(new TransactingError({ message: 'No guaranteedUnshieldedOffer found in intent' }));
      }

      const [registration, ...restRegistrations] = dustActions.registrations;
      if (!registration) {
        return yield* Either.left(new TransactingError({ message: 'No registrations found in dustActions' }));
      }

      return yield* LedgerOps.ledgerTry(() => {
        const signature = new SignatureEnabled(signatureData);
        const registrationWithSignature = new DustRegistration(
          signature.instance,
          registration.nightKey,
          registration.dustAddress,
          registration.allowFeePayment,
          signature,
        );
        const newDustActions = new DustActions(
          signature.instance,
          ProofMarker.preProof,
          dustActions.ctime,
          dustActions.spends,
          [registrationWithSignature, ...restRegistrations],
        );

        // make a copy of intent to avoid mutation
        const newIntent = Intent.deserialize<SignatureEnabled, PreProof, PreBinding>(
          signature.instance,
          ProofMarker.preProof,
          BindingMarker.preBinding,
          intent.serialize(),
        );
        newIntent.dustActions = newDustActions;

        const inputsLen = guaranteedUnshieldedOffer.inputs.length;
        const signatures: Signature[] = [];
        for (let i = 0; i < inputsLen; ++i) {
          signatures.push(guaranteedUnshieldedOffer.signatures.at(i) ?? signatureData);
        }
        newIntent.guaranteedUnshieldedOffer = guaranteedUnshieldedOffer.addSignatures(signatures);

        if (fallibleUnshieldedOffer) {
          const inputsLen = fallibleUnshieldedOffer.inputs.length;
          const signatures: Signature[] = [];
          for (let i = 0; i < inputsLen; ++i) {
            signatures.push(fallibleUnshieldedOffer.signatures.at(i) ?? signatureData);
          }
          newIntent.fallibleUnshieldedOffer = fallibleUnshieldedOffer.addSignatures(signatures);
        }

        // make a copy of transaction to avoid mutation
        const newTransaction = Transaction.deserialize<SignatureEnabled, PreProof, PreBinding>(
          signature.instance,
          ProofMarker.preProof,
          BindingMarker.preBinding,
          transaction.serialize(),
        );
        newTransaction.intents = newTransaction.intents!.set(1, newIntent);

        return newTransaction;
      });
    });
  }

  calculateFee(transaction: AnyTransaction, ledgerParams: LedgerParameters): bigint {
    return (
      transaction.feesWithMargin(ledgerParams, this.costParams.feeBlocksMargin) +
      (this.costParams.additionalFeeOverhead ?? 0n)
    );
  }

  /**
   * The fee the transactions would carry with `recipeInputs` attached as dust spends in a balancing intent. With no
   * inputs there is no intent to attach — an intent with empty `DustActions` is not well-formed — so it is the fee of
   * the transactions as they are. Nothing is persisted. `merged` lets a caller pricing several input sets against the
   * same transactions proof-erase and merge them once; it is derived from `transactions` when omitted.
   */
  dryRunFee(
    recipeInputs: ReadonlyArray<CoinWithValue<Dust>>,
    transactions: ReadonlyArray<FinalizedTransaction | UnprovenTransaction>,
    secretKey: DustSecretKey,
    state: CoreWallet,
    ttl: Date,
    currentTime: Date,
    ledgerParams: LedgerParameters,
    merged: Option.Option<MergedTransactions> = mergeErasedTransactions(transactions),
  ): bigint {
    const priced = EArray.match(recipeInputs, {
      onEmpty: () => Option.map(merged, (existing) => existing.transaction),
      onNonEmpty: (inputs) => {
        const [spends] = CoreWallet.spendCoins(state, secretKey, inputs, currentTime);
        const intent = Intent.new(ttl);
        intent.dustActions = new DustActions<SignatureEnabled, PreProof>(
          SignatureMarker.signature,
          ProofMarker.preProof,
          currentTime,
          [...spends],
          [],
        );
        const segmentId = pipe(
          merged,
          Option.map((existing) => existing.segmentId),
          Option.getOrElse(() => 1),
        );
        const balancing = Transaction.fromParts(this.networkId)
          .addIntent({ tag: 'specific', value: segmentId }, intent)
          .eraseProofs();
        return Option.some(
          pipe(
            merged,
            Option.match({ onNone: () => balancing, onSome: (existing) => existing.transaction.merge(balancing) }),
          ),
        );
      },
    });
    return pipe(
      priced,
      Option.match({ onNone: () => 0n, onSome: (transaction) => this.calculateFee(transaction, ledgerParams) }),
    );
  }

  static feeImbalance(transaction: AnyTransaction, totalFee: bigint): bigint {
    const [_, imbalance] =
      transaction
        .imbalances(0, totalFee)
        .entries()
        .find(([tt, _]) => tt.tag === 'dust') ?? [];

    return imbalance ?? 0n;
  }

  /**
   * Selects the dust inputs a balancing intent needs so that, merged with `transactions`, the result covers its own fee
   * — including the fee those inputs add — net of any dust the transactions already carry. `fee` is the total fee of
   * that merged result, the figure {@link estimateFee} reports; `recipeInputs` lists the selected coins in selection
   * order, each valued at the part of the shortfall it pays. Both are empty when the transactions already cover their
   * fee.
   *
   * Selection runs under the configured {@link CoinSelection} and is retried once largest-first only if that order
   * exhausts the pool; a selector that declines coins is honoured and reports insufficient funds directly.
   */
  computeBalancingRecipe(
    secretKey: DustSecretKey,
    state: CoreWallet,
    transactions: ReadonlyArray<FinalizedTransaction | UnprovenTransaction>,
    ttl: Date,
    currentTime: Date,
    ledgerParams: LedgerParameters,
  ): Either.Either<DustBalancingRecipe, WalletError> {
    return Either.gen(this, function* () {
      const merged = yield* LedgerOps.ledgerTry(() => mergeErasedTransactions(transactions));
      const standaloneFees = yield* LedgerOps.ledgerTry(() =>
        transactions.map((transaction) => this.calculateFee(transaction, ledgerParams)),
      );
      // `feeImbalance` nets the dust a transaction already carries (spends, registration allowances) against its own
      // fee. Adding the fees back isolates that dust, which counts toward coverage on every pass.
      const existingDust = yield* LedgerOps.ledgerTry(
        () =>
          BigIntOps.sumAll(
            EArray.zipWith(transactions, standaloneFees, (transaction, fee) =>
              TransactingCapabilityImplementation.feeImbalance(transaction, fee),
            ),
          ) + BigIntOps.sumAll(standaloneFees),
      );
      const baseFee = yield* LedgerOps.ledgerTry(() =>
        pipe(
          merged,
          Option.match({
            onNone: () => 0n,
            onSome: (existing) => this.calculateFee(existing.transaction, ledgerParams),
          }),
        ),
      );
      const coins = this.getCoins().getAvailableCoinsWithGeneratedDust(state, currentTime);
      const feeWith = (inputs: EArray.NonEmptyReadonlyArray<CoinWithValue<Dust>>) =>
        LedgerOps.ledgerTry(() =>
          this.dryRunFee(inputs, transactions, secretKey, state, ttl, currentTime, ledgerParams, merged),
        );
      const select = (coinSelection: CoinSelection) =>
        selectDustInputs({ coins, baseFee, existingDust, feeWith, coinSelection });
      return yield* Either.mapLeft(selectWithLargestFirstRetry(select, this.getCoinSelection()), toWalletError);
    });
  }

  estimateFee(
    secretKey: DustSecretKey,
    state: CoreWallet,
    transactions: ReadonlyArray<FinalizedTransaction | UnprovenTransaction>,
    ttl: Date,
    currentTime: Date,
    ledgerParams: LedgerParameters,
  ): Either.Either<bigint, WalletError> {
    return pipe(
      this.computeBalancingRecipe(secretKey, state, transactions, ttl, currentTime, ledgerParams),
      Either.map(({ fee }) => fee),
    );
  }

  balanceTransactions(
    secretKey: DustSecretKey,
    state: CoreWallet,
    transactions: ReadonlyArray<FinalizedTransaction | UnprovenTransaction>,
    ttl: Date,
    currentTime: Date,
    ledgerParams: LedgerParameters,
  ): Either.Either<[UnprovenTransaction, CoreWallet], WalletError> {
    const networkId = this.networkId;

    return pipe(
      this.computeBalancingRecipe(secretKey, state, transactions, ttl, currentTime, ledgerParams),
      Either.flatMap(({ recipeInputs }) =>
        LedgerOps.ledgerTry((): [UnprovenTransaction, CoreWallet] =>
          EArray.match(recipeInputs, {
            // The transactions already cover their fee. An intent with empty `DustActions` is not well-formed, so
            // there is nothing to add: an empty transaction merges into anything as the identity, and no dust is
            // booked as pending.
            onEmpty: () => [Transaction.fromParts(networkId), state],
            onNonEmpty: (inputs) => {
              const [spends, updatedState] = CoreWallet.spendCoins(state, secretKey, inputs, currentTime);
              const intent = Intent.new(ttl);
              intent.dustActions = new DustActions<SignatureEnabled, PreProof>(
                SignatureMarker.signature,
                ProofMarker.preProof,
                currentTime,
                [...spends],
                [],
              );
              const segmentId = pipe(
                mergeErasedTransactions(transactions),
                Option.map((existing) => existing.segmentId),
                Option.getOrElse(() => 1),
              );
              return [
                Transaction.fromParts(networkId).addIntent({ tag: 'specific', value: segmentId }, intent),
                updatedState,
              ];
            },
          }),
        ),
      ),
    );
  }

  revertTransaction(
    state: CoreWallet,
    transaction: UnprovenTransaction | TTransaction,
  ): Either.Either<CoreWallet, WalletError> {
    return Either.try({
      try: () => CoreWallet.revertTransaction(state, transaction),
      catch: (err) => {
        return new OtherWalletError({
          message: `Error while reverting transaction ${transaction.identifiers().at(0)!}`,
          cause: err,
        });
      },
    });
  }
}
