services:
  proof-server:
    image: 'ghcr.io/midnight-ntwrk/proof-server:9.0.0-alpha.1'
    container_name: proof-server_$TESTCONTAINERS_UID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - '127.0.0.1::6300'
    environment:
      RUST_BACKTRACE: 'full'
      EXTRA_ARGS: -v
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:6300/version']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  indexer:
    image: 'ghcr.io/midnight-ntwrk/indexer-standalone:4.3.4-pre-alpha.5-l9a1-n2a1-bridge-and-public-events-balances-fix-5d2a847'
    container_name: indexer_$TESTCONTAINERS_UID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - '127.0.0.1::8088'
    environment:
      RUST_LOG: 'indexer=debug,chain_indexer=debug,indexer_api=debug,wallet_indexer=debug,indexer_common=debug,fastrace_opentelemetry=off,info'
      APP__INFRA__NODE__URL: 'ws://node:9944'
      APP__APPLICATION__NETWORK_ID: 'undeployed'
      APP__INFRA__SECRET: '${APP_INFRA_SECRET}'
      APP__INFRA__SPO_NODE__URL: 'ws://node:9944'
      APP__INFRA__SPO_NODE__BLOCKFROST_ID: 'e2e-test-dummy'

    healthcheck:
      test: ['CMD-SHELL', 'curl -fs http://localhost:8088/ready']
      interval: 5s
      timeout: 5s
      retries: 36
      start_period: 60s
    depends_on:
      node:
        condition: service_healthy
  node:
    image: 'ghcr.io/midnight-ntwrk/midnight-node:2.0.0-alpha.1'
    container_name: node_$TESTCONTAINERS_UID
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    ports:
      - '127.0.0.1::9944'
    volumes:
      - node-data:/data
    healthcheck:
      test:
        - 'CMD-SHELL'
        - >
          curl -fs -H 'Content-Type: application/json' -d
          '{"id":1,"jsonrpc":"2.0","method":"chain_getBlockHash","params":[1]}' http://localhost:9944 | grep -q
          '"result":"0x'
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s
    environment:
      CFG_PRESET: 'dev'
      SIDECHAIN_BLOCK_BENEFICIARY: '04bcf7ad3be7a5c790460be82a713af570f22e0f801f6659ab8e84a52be6969e'

volumes:
  node-data:
