name: CI

env:
  MIDNIGHT_GH_USER: ${{ secrets.GH_USERNAME }}
  MIDNIGHT_GH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}
  NETWORK: undeployed
  DEPLOYMENT: local
  APP_INFRA_SECRET: ${{ secrets.APP_INFRA_SECRET }}

on:
  workflow_dispatch:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        id: setup-node
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          token: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Enable corepack
        run: corepack enable

      - name: Check tool versions
        run: |
          node --version
          corepack --version
          yarn --version

      - name: Log in to GitHub Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: 'https://ghcr.io'
          username: ${{ env.MIDNIGHT_GH_USER }}
          password: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ env.MIDNIGHT_GH_TOKEN }}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run dist
        run: yarn dist

      - name: Save turbo cache
        if: always()
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-build-${{ github.run_attempt }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            packages/*/dist/**
            packages/*/tsconfig.*.tsbuildinfo

  general-checks:
    name: General Checks
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        id: setup-node
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          token: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Enable corepack
        run: corepack enable

      - name: Check tool versions
        run: |
          node --version
          corepack --version
          yarn --version

      - name: Log in to GitHub Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: 'https://ghcr.io'
          username: ${{ env.MIDNIGHT_GH_USER }}
          password: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ env.MIDNIGHT_GH_TOKEN }}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Restore turbo cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-general-${{ github.run_attempt }}
          restore-keys: |
            turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-general-
            turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-build-

      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .

      # The following 4 steps are the equivalent of running `yarn verify:check`/`turbo verify:check`
      # They are separated into individual steps to give better visibility of the errors in the ci.
      # Future changes to verify:check should be reflected in these steps.
      - name: Run typecheck
        run: yarn typecheck

      - name: Run format check
        run: yarn format:check

      - name: Run linter
        run: yarn lint

      - name: Check barrel exports
        run: yarn check-barrel-exports

      - name: Save turbo cache
        if: always()
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-general-${{ github.run_attempt }}

  tests:
    name: Tests
    needs: [general-checks]
    runs-on: ubuntu-latest-16-core-x64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        id: setup-node
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          token: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Enable corepack
        run: corepack enable

      - name: Check tool versions
        run: |
          node --version
          corepack --version
          yarn --version

      - name: Log in to GitHub Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: 'https://ghcr.io'
          username: ${{ env.MIDNIGHT_GH_USER }}
          password: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ env.MIDNIGHT_GH_TOKEN }}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Restore turbo cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-general-${{ github.run_attempt }}
          restore-keys: |
            turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-general-

      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .

      - name: Pre-pull Docker images
        run: docker compose -f infra/compose/docker-compose-dynamic.yml pull

      - name: Run tests
        run: yarn test

      - name: Run smoke e2e tests
        run: |
          yarn dlx turbo test-undeployed -- -t @smoke

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # v6
        if: success() || failure()
        with:
          check_name: 'Test Results Wallet SDK'
          report_paths: |
            **/test-report*.xml

  build-publish:
    name: Build for Publishing
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        id: setup-node
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          token: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Enable corepack
        run: corepack enable

      - name: Check tool versions
        run: |
          node --version
          corepack --version
          yarn --version

      - name: Log in to GitHub Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: 'https://ghcr.io'
          username: ${{ env.MIDNIGHT_GH_USER }}
          password: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ env.MIDNIGHT_GH_TOKEN }}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run dist:publish
        run: yarn dist:publish

      - name: Save turbo cache
        if: always()
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-build-publish-${{ github.run_attempt }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: build-publish-artifacts-${{ github.run_id }}
          path: |
            packages/*/dist/**
            packages/*/tsconfig.*.tsbuildinfo

  publish-checks:
    name: Publish Checks
    needs: [build-publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        id: setup-node
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          token: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Enable corepack
        run: corepack enable

      - name: Check tool versions
        run: |
          node --version
          corepack --version
          yarn --version

      - name: Log in to GitHub Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: 'https://ghcr.io'
          username: ${{ env.MIDNIGHT_GH_USER }}
          password: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ env.MIDNIGHT_GH_TOKEN }}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Restore turbo cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-build-publish-${{ github.run_attempt }}
          restore-keys: |
            turbo-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}-build-publish-

      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-publish-artifacts-${{ github.run_id }}
          path: .
        continue-on-error: true

      - name: Run publint
        run: yarn publint
