name: E2E tests - local - nodejs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  MIDNIGHT_GH_USER: ${{ secrets.GH_USERNAME }}
  MIDNIGHT_GH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
  NETWORK: 'undeployed'
  APP_INFRA_SECRET: ${{ secrets.APP_INFRA_SECRET }}

permissions: {}

jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-latest-8-core-x64
    timeout-minutes: 80
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        version: [22]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          token: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Log in to GitHub Container registry
        uses: docker/login-action@3227f5311cb93ffd14d13e65d8cc400d30f4dd8a
        with:
          registry: 'https://ghcr.io'
          username: ${{ env.MIDNIGHT_GH_USER }}
          password: ${{ env.MIDNIGHT_GH_TOKEN }}

      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ env.MIDNIGHT_GH_TOKEN }}"

      - name: Build wallet and install dependencies
        run: |
          yarn install
          yarn turbo dist

      - name: Run e2e tests
        run: |
          yarn turbo test-undeployed

      - name: Publish wallet TS Test Report
        uses: dorny/test-reporter@b082adf0eced0765477756c2a610396589b8c637 # v2
        if: success() || failure()
        with:
          name: Wallet TS packages Junit Tests Report
          reporter: java-junit
          path: |
            ./packages/e2e-tests/reports/test-report.xml
