name: Healthcheck - qanet

on:
  workflow_dispatch:
    inputs:
      skip_cache:
        type: boolean
        description: Skip downloading sync cache (force fresh wallet sync)
        required: false
        default: false
  schedule:
    - cron: '0 7,16 * * *'

jobs:
  test:
    name: Healthcheck tests
    uses: ./.github/workflows/e2e-tests.yml
    with:
      network: qanet
      modifier: '-t @healthcheck'
      skip_cache: ${{ inputs.skip_cache || false }}
    secrets:
      MIDNIGHTCI_PACKAGES_WRITE: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
      APP_INFRA_SECRET: ${{ secrets.APP_INFRA_SECRET }}
      E2E_TESTS_SEED: ${{ secrets.E2E_TESTS_SEED }}
      E2E_TESTS_SEED2: ${{ secrets.E2E_TESTS_SEED2 }}
      E2E_TESTS_SEED_STABLE: ${{ secrets.E2E_TESTS_SEED_STABLE }}
      E2E_TESTS_NT_SEED: ${{ secrets.E2E_TESTS_NT_SEED }}
      E2E_TESTS_NT_SEED2: ${{ secrets.E2E_TESTS_NT_SEED2 }}
