name: Healthcheck - preprod

on:
  workflow_dispatch:
    inputs:
      skip_cache:
        type: boolean
        description: Skip downloading sync cache (force fresh wallet sync)
        required: false
        default: false
  schedule:
    - cron: '0 7,16 * * *'

jobs:
  test:
    name: Healthcheck tests
    uses: ./.github/workflows/e2e-tests.yml
    with:
      network: preprod
      modifier: '-t @healthcheck'
      skip_cache: ${{ inputs.skip_cache || false }}
    secrets: inherit
