name: Healthcheck - testnet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

permissions: {}

jobs:
  test:
    name: Healthcheck tests
    uses: ./.github/workflows/e2e-tests.yml
    with:
      network: testnet
      deployment: testnet
      modifier: "-t @healthcheck"
    secrets: inherit
